volumes:
  _volumes:
  _sessions:

networks:
  internal:
    driver: bridge
    
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak:
    container_name: keycloak
    # env_file:
    #   - path: .env
    #     required: true
    #   - path: .env.production
    #     required: false

    build:
      context: ./keycloak/   
    # image: quay.io/keycloak/keycloak:23.0.5
    environment:
      # https://qiita.com/uturned0/items/e9256c48ccba6f588d79
      KC_DB: mysql
      KC_DB_URL_HOST: ${MYSQL_HOST:-localhost}
      KC_DB_USERNAME: ${MYSQL_USER:-user}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD:-password}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-password}
      
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      #to keep compatible with other services that are expecting /auth
      KC_HTTP_RELATIVE_PATH: /auth

      # https://stackoverflow.com/a/75649421
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: "edge"
      JAVA_OPTS_APPEND: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/import -Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./keycloak/import:/import
      - ./keycloak/api-key-module/target/deploy:/opt/keycloak/providers/

    ports:
      - 8080:8080
    command:
      - start-dev
    networks:
      - internal

  # for demonstration
  dashboard-service:
    build:
      context: ./dashboard-service/   
    environment:
      REALM_NAME: example
    ports:
      - 8081:8081

