volumes:
  _volumes:

networks:
  internal:
    driver: bridge

services:
  dashboard:
    environment:
      KEY_CLOAK_AUTH_URL: http://keycloak:8080/auth/realms/kana-api

  keycloak-mysql-db:
    image: mysql:8.0.27
    container_name: keycloak-mysql
    volumes:
      - ./_volumes/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: digital
      MYSQL_DATABASE: keycloak
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

    healthcheck:
      test: mysql keycloak --user=dbuser --password='dbpassword' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

  keycloak:
    depends_on:
      - keycloak-mysql-db
      # keycloak-mysql-db:
      #   condition: "service_healthy"
    environment:
      # https://qiita.com/uturned0/items/e9256c48ccba6f588d79
      KC_DB_URL_HOST: keycloak-mysql-db
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: digital
      KC_HOSTNAME: localhost

  # for debugging
  # phpmyadmin:
  #   container_name: keycloak-phpmyadmin
  #   image: phpmyadmin:latest
  #   ports:
  #     - 3001:80
  #   environment:
  #     PMA_HOST: keycloak-mysql-db
  #     UPLOAD_LIMIT: 1G
  #   # networks:
  #   #   - internal
  #   # depends_on:
  #   #   - keycloak-mysql-db
  #   volumes:
  #     - ./_sessions:/sessions
  #   networks:
  #     - internal