services:
  dashboard:
    env_file:
      - path: .env
        required: true
    environment:
      KEY_CLOAK_AUTH_URL: http://ec2-52-68-52-194.ap-northeast-1.compute.amazonaws.com/auth/realms/kana-api

  keycloak:
    env_file:
      - path: .env
        required: true
    environment:
      KC_DB_URL_HOST: ${MYSQL_HOST}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}

