networks:
  internal:
    driver: bridge

services:
  dashboard-service:
    environment:
      KC_URL: http://localhost

  keycloak-mysql-db:
    image: mysql:8.0.27
    container_name: keycloak-mysql
    volumes:
      - ./_volumes/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: digital
      MYSQL_DATABASE: keycloak
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

    ports:
      - 3306:3306
    networks:
      - internal
    healthcheck:
      test: mysql keycloak --user=dbuser --password='dbpassword' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5  

  keycloak:
    depends_on:
      keycloak-mysql-db:
        condition: "service_healthy"
    links:
      - keycloak-mysql-db
    environment:
      # https://qiita.com/uturned0/items/e9256c48ccba6f588d79
      KC_DB_URL_HOST: keycloak-mysql-db
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: digital
      KC_HOSTNAME: localhost

  # for debugging
  phpmyadmin:
    container_name: keycloak-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 3001:80
    environment:
      PMA_HOST: keycloak-mysql-db
      UPLOAD_LIMIT: 1G
    networks:
      - internal
    depends_on:
      - keycloak-mysql-db
    links:
      - keycloak-mysql-db
    volumes:
      - ./_sessions:/sessions